### ISSUE TITLE
Pull replication gets stuck in Active with more completed changes than pending changes

### ISSUE THREAD

**Issue by ryanthompson0123** [couchbase/couchbase-lite-net#755]
I'm having a problem that's affecting several customers of mine where pull replications get stuck in Active and never terminate. When a replication gets into this state, I can't even stop it by calling pull.Stop();

The strange thing is that when the replication gets stuck, the last line of the log shows:

`INFO) SYNC (Replication): [10] 2016-10-5 10:51:49.473-06:00 NotifyChangeListeners (4120/4080, state=Running (batch=0, net=0))`

I've tested this multiple times with a fresh database, and sometimes it's successful, and other times it gets stuck. The changes count when it gets stuck is usually different, but the first number is always greater than the second, which makes no sense.

I've attached two logs of my test application having this issue. The second log has the log output set to full debug mode. My test application is really simple - it just has a button that triggers a pull replication like this:

    private void TrySync ()
    {
        var database = Manager.SharedInstance.GetDatabase ("testdb");

        Log.Level = Log.LogLevel.Debug;

        if (PullReplication == null) {
            var authenticator = AuthenticatorFactory.CreateBasicAuthenticator ("username", "password");

            var pull = database.CreatePullReplication (new Uri ("https://my.server.com:4984/sandbox_sync_gateway"));

            pull.Authenticator = authenticator;
            pull.Changed += Pull_Changed;
            PullReplication = pull;
        }

        PullReplication.Start ();
    }

This could certainly be a problem on my end, but at this point I have no idea how to diagnose it.

We are running Couchbase Lite 1.3.0 and Sync Gateway 1.3.0.
Please let me know if there's any more information I can provide.

[cbl-problem-log.txt](https://github.com/couchbase/couchbase-lite-net/files/511842/cbl-problem-log.txt)
[cbl-problem-log2.txt](https://github.com/couchbase/couchbase-lite-net/files/511843/cbl-problem-log2.txt)

**Comment by borrrden** [comment]
There is something really odd going on here.  The log is full of errors complaining about, basically, the doc IDs not matching between the changes feed and the documents pulled from bulk get (.  The problem of the completed changes getting ahead of the total changes is something I've seen before and I thought at this point it was fixed (usually it's a case of failed revisions not getting marked completed).  Does the same problem happen for you with 1.3.1?

**Comment by ryanthompson0123** [comment]
I have some more information on this. We upgraded our sync gateways and the mobile libraries to version 1.3.1, and we are still seeing this happen to about 10% of our user base. It's a big problem for us because once a user gets into this state, the only fix is to delete the mobile database and start fresh.

I wish I could provide more information on how to get into this state. I can give you a database file I pulled from a device that was exhibiting this behavior, but I'd rather not post it directly here. Just to give a little more background, here's some more information on our sync use case.

We have a set of business requirements that require us to control when and if a user is allowed to sync their data. A couple of examples would be: deactivate a user so they can't sync at all, force an app upgrade before sync, force a remote db wipe, etc. So we can't really use the continuous sync mode.

What we've done is set up a loop to run one shot push / pull replications every 60 seconds. Each iteration of the loop is 'gated' - it calls an endpoint on our server application to determine if it's okay to sync and if not, what action it's supposed to take. We used to run the push and pull replications simultaneously, but we recently changed them to run pull first, then push, in a blind attempt to address this issue. It hasn't helped.

Let me know if you want any more detailed information, or if there's any steps I can take to troubleshoot this on my end.

**Comment by ryanthompson0123** [comment]
One other piece of information I failed to mention:

On the day I initially reported this bug, I spent the whole day investigating it. I was able to consistently reproduce the issue all day until around 4:45 PM when our DevOps guys rebooted our sync gateway cluster. After that, everything worked fine. Then slowly over a period of days, the problem started to reappear. Maybe we have our sync gateway configured wrong, so if any of this rings any bells, let me know.

**Comment by borrrden** [comment]
How about on the sync gateway side?  Do you have a set of logs from there?

**Comment by jonfunkhouser** [comment]
I've encountered this issue in one of our development environments. I can consistently reproduce the issue in this environment, and I've spent the last day investigating it.

I'm running a non-continuous pull replication on a fresh database. This replication gets stuck at 91695/91674.

Library Versions:
Couchbase Lite: 1.3.1 (I've added additional logging, and the issue is still reproducible)
Sync Gateway: 1.1.1-10 (I'm working on setting up an environment with 1.3.1 to confirm the issue still occurs)

The issue appears to be related to how the library handles missing revisions returned from the ```BulkGet``` API.

I found 9 revisions that are responsible for incrementing the completion count multiple times. In total, these are responsible for 21 additional increments of the completion count, which matches the overage in the total sync progress.

This table lists the revisions, and the locations in ```Puller``` where the completion count is incremented. The order of locations in each row is also the order in which they were called.

RevId | Total # Increments | Increment Locations
----- | ------------------ | -------------------
1-153e4bac58e79b2fab170dd593818911 | 4 | [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [DontRetryRevDownload](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L385), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390)
1-2eb557979e9f9c5c2f86cd729bd76137 | 4 | [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [DontRetryRevDownload](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L385), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390)
3-59e0b355b29e04bd994d00fe5fd6b11b | 2 | [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [ErrorPullingRevision](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L592)
4-f5244dbfa854d027ca1da321471c136d | 2 | [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [ErrorPullingRevision](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L592)
4-921ffcf5d64a96119ccc523ecf672026 | 2 | [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [ErrorPullingRevision](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L592)
27-c475fd9161b83a7bb3a6c5cef08b622c | 4 | [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [DontRetryRevDownload](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L385), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390)
2-1e662ee589f6a22b990f37a5d2d45a43 | 4 | [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [DontRetryRevDownload](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L385), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390)
5-4c99a7a621b73b6de9f813e47d8905d4 | 4 | [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [DontRetryRevDownload](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L385), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390)
5-a2ae28da756a3b4bf3d3e420aabcc72c | 4 | [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390), [DontRetryRevDownload](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L385), [RevNotReturnedByBulkGet](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390)

I then started to add more logging to ```Puller.PullBulkRevisions``` to continue my investigation. I eventually found that the [unexpected rev else block](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L348) was called 21 times. I flattened the ```DocumentProperties``` to my log file in this case and got (the doc_ids are redacted):

```
error=not_found,id=doc_id_a,reason=missing,rev=1-153e4bac58e79b2fab170dd593818911,status=404
error=not_found,id=doc_id_b,reason=missing,rev=1-2eb557979e9f9c5c2f86cd729bd76137,status=404
error=not_found,id=doc_id_a,reason=missing,rev=1-153e4bac58e79b2fab170dd593818911,status=404
error=not_found,id=doc_id_b,reason=missing,rev=1-2eb557979e9f9c5c2f86cd729bd76137,status=404
error=not_found,id=doc_id_a,reason=missing,rev=1-153e4bac58e79b2fab170dd593818911,status=404
error=not_found,id=doc_id_b,reason=missing,rev=1-2eb557979e9f9c5c2f86cd729bd76137,status=404
error=not_found,id=doc_id_c,reason=missing,rev=3-59e0b355b29e04bd994d00fe5fd6b11b,status=404
error=not_found,id=doc_id_d,reason=missing,rev=4-f5244dbfa854d027ca1da321471c136d,status=404
error=not_found,id=doc_id_e,reason=missing,rev=4-921ffcf5d64a96119ccc523ecf672026,status=404
error=not_found,id=doc_id_f,reason=missing,rev=27-c475fd9161b83a7bb3a6c5cef08b622c,status=404
error=not_found,id=doc_id_g,reason=missing,rev=2-1e662ee589f6a22b990f37a5d2d45a43,status=404
error=not_found,id=doc_id_f,reason=missing,rev=27-c475fd9161b83a7bb3a6c5cef08b622c,status=404
error=not_found,id=doc_id_g,reason=missing,rev=2-1e662ee589f6a22b990f37a5d2d45a43,status=404
error=not_found,id=doc_id_f,reason=missing,rev=27-c475fd9161b83a7bb3a6c5cef08b622c,status=404
error=not_found,id=doc_id_g,reason=missing,rev=2-1e662ee589f6a22b990f37a5d2d45a43,status=404
error=not_found,id=doc_id_h,reason=missing,rev=5-4c99a7a621b73b6de9f813e47d8905d4,status=404
error=not_found,id=doc_id_i,reason=missing,rev=5-a2ae28da756a3b4bf3d3e420aabcc72c,status=404
error=not_found,id=doc_id_h,reason=missing,rev=5-4c99a7a621b73b6de9f813e47d8905d4,status=404
error=not_found,id=doc_id_i,reason=missing,rev=5-a2ae28da756a3b4bf3d3e420aabcc72c,status=404
error=not_found,id=doc_id_h,reason=missing,rev=5-4c99a7a621b73b6de9f813e47d8905d4,status=404
error=not_found,id=doc_id_i,reason=missing,rev=5-a2ae28da756a3b4bf3d3e420aabcc72c,status=404
```

Ok! So these 9 revisions are missing on the server, and we're trying to download them multiple times. The API response for missing revs in [the latest revision of the BulkGet API](https://github.com/couchbase/sync_gateway/blob/master/rest/bulk_api.go#L358) appears to be identical.

I have no experience with this code, but it looks like the following issues are contributing to the problem:

* Missing revisions never reach the "RevisionFailed" code block because of [this return statement](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L349)
* [rev.Sequence is never set](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L363) for missing revisions. ```DocID``` and ```RevID``` are null for these revisions since the json uses the keys ```id``` and ```rev```.
* Missing revisions should be removed from ```remainingRevs``` when [pendingSequences is updated](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L363), so the completion count is not updated again for this revision [here](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication/Puller.cs#L390)

Hopefully this helps. Please let me know if you need any more information. I'll try to confirm if this issue occurs with SG 1.3.1.

**Comment by borrrden** [comment]
Thanks for this analysis, it is probably the single most methodical comment I've ever received here!  The last bullet point in the last section might be the interesting section.

**Comment by borrrden** [comment]
I think I see what is going on here.  Can you share the Couchbase log messages that start with 'Received unexpected rev'?  Do they have proper revision IDs in those messages?  My theory now is that these missing rev objects don't have a rev ID since they were returned as 404 and so they fail to get removed (and thus trigger the unexpected rev message).

**Comment by borrrden** [comment]
OH, this actually looks like a regression introduced in 1.3.0 (I missed the fact that bulk get is returning `id` and `rev` vs the usual `_id` and `_rev`).  I can throw up a change on a branch real quick that should take care of that.  Whether or not it fixes OPs issue I'm not sure.

**Comment by jonfunkhouser** [comment]
I ran this new build against my dev environment and it looks like the issue is fixed (at least for me):

```
2016-10-24 20:56:06,940 [13] INFO  SYNC (Replication) [(null)] - Puller a0614015-5b02-4464-b84a-de9f2081b46c progress 91674 / 91674
2016-10-24 20:56:06,940 [13] INFO  SYNC (Replication) [(null)] - NotifyChangeListeners (91674/91674, state=Running (batch=0, net=0))
2016-10-24 20:56:06,941 [13] DEBUG SYNC (Replication) [(null)] - Non-continuous replication caught up, firing StopGraceful...
2016-10-24 20:56:06,942 [13] DEBUG SYNC (Replication) [(null)] - Preparing to fire StopGraceful
2016-10-24 20:56:06,943 [13] DEBUG SYNC (Replication) [(null)] - Running => Stopping (a0614015-5b02-4464-b84a-de9f2081b46c)
2016-10-24 20:56:06,944 [13] DEBUG SYNC (Replication) [(null)] - Running => Stopping (a0614015-5b02-4464-b84a-de9f2081b46c)
2016-10-24 20:56:06,945 [13] INFO  SYNC (Replication) [(null)] - NotifyChangeListeners (91674/91674, state=Stopping (batch=0, net=0))
2016-10-24 20:56:06,947 [13] INFO  SYNC (Replication) [(null)] - a0614015-5b02-4464-b84a-de9f2081b46c: Stop Graceful...
2016-10-24 20:56:06,956 [13] DEBUG SYNC (Replication) [(null)] - Preparing to fire StopImmediate
2016-10-24 20:56:06,957 [13] DEBUG SYNC (Replication) [(null)] - Stopping => Stopped (a0614015-5b02-4464-b84a-de9f2081b46c)
2016-10-24 20:56:06,958 [13] INFO  SYNC (Replication) [(null)] - Puller a0614015-5b02-4464-b84a-de9f2081b46c Stopping
2016-10-24 20:56:06,960 [13] INFO  SYNC (Replication) [(null)] - Puller a0614015-5b02-4464-b84a-de9f2081b46c checkpointing sequence=605055
```

Thank you for your help! I'll continue running more tests tomorrow.

**Comment by borrrden** [comment]
@ryanthompson123 Can you also see if this branch solves your problem?

**Comment by ryanthompson0123** [comment]
@borrrden I tested this with a database that was in the stuck state, and it does seem to have resolved the issue.

**Comment by borrrden** [comment]
Excellent.  Thanks for the response.
